services:
  app:
    build: .
    container_name: docker-webapi 
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase  
    volumes:
      - .:/flaskwebapi